# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

euclnormC <- function(x) {
    .Call(`_forecastcalibration_euclnormC`, x)
}

copulapitC <- function(y, dat) {
    .Call(`_forecastcalibration_copulapitC`, y, dat)
}

esC_sample <- function(y, dat) {
    .Call(`_forecastcalibration_esC_sample`, y, dat)
}

esC_split <- function(y, dat1, dat2) {
    .Call(`_forecastcalibration_esC_split`, y, dat1, dat2)
}

